import java.net.URI
import java.util.Base64

plugins {
    id("com.android.application")
    // The Flutter Gradle Plugin must be applied after the Android and Kotlin Gradle plugins.
    id("dev.flutter.flutter-gradle-plugin")
}

// MOB-018 / ADR-16: debug and profile builds may use cleartext HTTP and WS only to the
// host of the API_BASE_URL dart-define. The config is generated per build, so no LAN IP
// is committed. Release builds get no network security config at all, so Android's
// default (no cleartext) applies.
val apiCleartextHost: String = run {
    // The Flutter tool passes --dart-define values as base64("KEY=VALUE"), comma-separated.
    val defines = (project.findProperty("dart-defines") as String?)
        ?.split(",")
        ?.filter { it.isNotBlank() }
        ?.map { String(Base64.getDecoder().decode(it), Charsets.UTF_8) }
        ?.associate { it.substringBefore("=") to it.substringAfter("=", "") }
        .orEmpty()
    val url = defines["API_BASE_URL"].orEmpty()
    val host = if (url.startsWith("http://")) URI(url).host.orEmpty() else ""
    // Fail closed: anything that is not a plain host name or IPv4 address allows no cleartext.
    if (Regex("^[A-Za-z0-9.-]{1,253}$").matches(host)) host else ""
}

abstract class NetworkSecurityConfigTask : DefaultTask() {
    @get:Input
    abstract val cleartextHost: Property<String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val host = cleartextHost.get()
        val domainConfig = if (host.isEmpty()) {
            ""
        } else {
            """
            |    <domain-config cleartextTrafficPermitted="true">
            |        <domain includeSubdomains="false">$host</domain>
            |    </domain-config>
            |""".trimMargin()
        }
        val xml = outputDir.get().file("xml/network_security_config.xml").asFile
        xml.parentFile.mkdirs()
        xml.writeText(
            """
            |<?xml version="1.0" encoding="utf-8"?>
            |<!-- Generated by build.gradle.kts (MOB-018). Do not edit. -->
            |<network-security-config>
            |    <base-config cleartextTrafficPermitted="false" />
            |$domainConfig</network-security-config>
            |""".trimMargin(),
        )
    }
}

androidComponents {
    onVariants { variant ->
        if (variant.buildType == "debug" || variant.buildType == "profile") {
            val task = tasks.register<NetworkSecurityConfigTask>(
                "generate${variant.name.replaceFirstChar { it.uppercase() }}NetworkSecurityConfig",
            ) {
                cleartextHost.set(apiCleartextHost)
            }
            variant.sources.res?.addGeneratedSourceDirectory(task, NetworkSecurityConfigTask::outputDir)
        }
    }
}

android {
    namespace = "com.tanzeel.oncallpilot"
    compileSdk = flutter.compileSdkVersion
    ndkVersion = flutter.ndkVersion

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId = "com.tanzeel.oncallpilot"
        // You can update the following values to match your application needs.
        // For more information, see: https://flutter.dev/to/review-gradle-config.
        minSdk = 24
        targetSdk = flutter.targetSdkVersion
        versionCode = flutter.versionCode
        versionName = flutter.versionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig = signingConfigs.getByName("debug")
        }
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}

flutter {
    source = "../.."
}
